source "https://supermarket.getchef.com"

metadata

cookbook 'runit', '=1.5.10'
cookbook 'iptables'
cookbook 'openvpn_client', path: '../openvpn_client'
cookbook 'transmission'
cookbook 'chef-client'
