name             'transmission_wrapper'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures transmission_wrapper'
long_description 'Installs/Configures transmission_wrapper'
version          '0.1.0'
depends          'runit', '=1.5.10'
depends          'iptables'
depends          'openvpn_client'
depends          'transmission'
depends          'chef-client'
