name             'transmission'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures transmission'
long_description 'Installs/Configures transmission'
version          '0.2.0'
depends          'runit', '=1.5.10'
depends          'chef-client'
