name             'transmission'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures transmission'
long_description 'Installs/Configures transmission'
version          '0.1.0'
