actions :install
default_action :install

attribute :service, :kind_of => [String], :name_attribute => true

attribute :user, :kind_of => [String], :default => 'debian-transmission'
attribute :group, :kind_of => [String], :default => 'debian-transmission'
attribute :info_dir, :kind_of => [String], :default => '/var/lib/transmission-daemon/info'

attribute :settings, :kind_of => [Hash], :default => {
  "alt-speed-down" => 1000,
  "alt-speed-enabled" => true,
  "alt-speed-time-begin" => 540,
  "alt-speed-time-day" => 127,
  "alt-speed-time-enabled" => false,
  "alt-speed-time-end" => 1020,
  "alt-speed-up" => 20,
  "bind-address-ipv4" => "0.0.0.0",
  "bind-address-ipv6" => "::",
  "blocklist-enabled" => false,
  "blocklist-url" => "http://www.example.com/blocklist",
  "cache-size-mb" => 1024,
  "dht-enabled" => true,
  "download-dir" => "/var/lib/transmission-daemon/downloads",
  "download-limit" => 100,
  "download-limit-enabled" => 0,
  "download-queue-enabled" => true,
  "download-queue-size" => 50,
  "encryption" => 1,
  "idle-seeding-limit" => 5,
  "idle-seeding-limit-enabled" => true,
  "incomplete-dir" => "/var/lib/transmission-daemon/incomplete",
  "incomplete-dir-enabled" => true,
  "lpd-enabled" => false,
  "max-peers-global" => 2000,
  "message-level" => 2,
  "peer-congestion-algorithm" => "",
  "peer-id-ttl-hours" => 6,
  "peer-limit-global" => 2000,
  "peer-limit-per-torrent" => 2000,
  "peer-port" => 49777,
  "peer-port-random-high" => 65535,
  "peer-port-random-low" => 49152,
  "peer-port-random-on-start" => true,
  "peer-socket-tos" => "default",
  "pex-enabled" => true,
  "port-forwarding-enabled" => false,
  "preallocation" => 1,
  "prefetch-enabled" => 1,
  "queue-stalled-enabled" => true,
  "queue-stalled-minutes" => 30,
  "ratio-limit" => 0,
  "ratio-limit-enabled" => true,
  "rename-partial-files" => true,
  "rpc-authentication-required" => false,
  "rpc-bind-address" => "0.0.0.0",
  "rpc-enabled" => true,
  "rpc-port" => 9091,
  "rpc-url" => "/transmission/",
  "rpc-username" => "",
  "rpc-whitelist" => "0.0.0.0",
  "rpc-whitelist-enabled" => false,
  "scrape-paused-torrents-enabled" => true,
  "script-torrent-done-enabled" => false,
  "script-torrent-done-filename" => "",
  "seed-queue-enabled" => false,
  "seed-queue-size" => 10,
  "speed-limit-down" => 100,
  "speed-limit-down-enabled" => false,
  "speed-limit-up" => 20,
  "speed-limit-up-enabled" => true,
  "start-added-torrents" => false,
  "trash-original-torrent-files" => false,
  "umask" => 18,
  "upload-limit-enabled" => 1,
  "upload-slots-per-torrent" => 14,
  "utp-enabled" => true,
  "watch-dir" => "/var/lib/transmission-daemon/watch",
  "watch-dir-enabled" => false
}
